// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by flutter/tool/emit_dart.py from flutter/tool/theme_tokens.json
// (token codegen pipeline stages 2-3, flutter/docs/ARCHITECTURE.md section 4.3).
// Regenerate: python3 flutter/tool/gen_tokens.py && python3 flutter/tool/emit_dart.py
// Drift gate:  both scripts support --check (byte-compare, nonzero exit).
//
// Inputs:
//   theme_tokens.json sha256: 3637b188b1b39cb7514f967e29e67177a2d921414b2413da49a76b4813f489d7
// Upstream Java sources (paths + sha256 recorded in theme_tokens.json meta):
//   Theme.java: 12edf137d084f44989269d8f5914d17055cc885b307db5e9de8ab5acdf1a84ef
//   ThemeColors.java: 357f9eaf6b0eccd1924344bd60f33e3a0cdedced88025de2edf0e50f2350c362
//   bluebubbles.attheme: b1829c34447c8b0db06477c99d8c41f15a50c0db8b2fa8d3e4f693c29e88f69b
//   darkblue.attheme: 6922327115c412ef24cacc21af0546cd23dccab6e1f94e320a51332eed344bc0
//   arctic.attheme: 7e2ea3968b982b49b3eb5b9e030d88ba30806a1cb23c477e6e7b94397e1c6c74
//   day.attheme: a90cad2c5914a181db8500f63f39303782157694098a2ed81744345a334152d3
//   night.attheme: 8f0ab17a18ec6bdcba4907bf869acfcd985ebce350d6854befbbb2089fd57978
//
// Output is dartfmt-clean by construction: `dart format` must be a no-op
// on this file (enforced in CI with `dart format --set-exit-if-changed`).

import 'theme_blue.g.dart';
import 'theme_dark_blue.g.dart';
import 'theme_arctic_blue.g.dart';
import 'theme_day.g.dart';
import 'theme_night.g.dart';

export 'default_colors.g.dart';
export 'theme_blue.g.dart';
export 'theme_dark_blue.g.dart';
export 'theme_arctic_blue.g.dart';
export 'theme_day.g.dart';
export 'theme_night.g.dart';

/// Bundled sparse theme overlays keyed by their Android registration name
/// (Theme.java static init; 'Blue' is the default day theme and 'Dark Blue'
/// the default night theme).
const Map<String, Map<int, int>> kBundledThemes = <String, Map<int, int>>{
  'Blue': kBlueTheme,
  'Dark Blue': kDarkBlueTheme,
  'Arctic Blue': kArcticBlueTheme,
  'Day': kDayTheme,
  'Night': kNightTheme,
};
