// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by flutter/tool/emit_dart.py from flutter/tool/theme_tokens.json
// (token codegen pipeline stages 2-3, flutter/docs/ARCHITECTURE.md section 4.3).
// Regenerate: python3 flutter/tool/gen_tokens.py && python3 flutter/tool/emit_dart.py
// Drift gate:  both scripts support --check (byte-compare, nonzero exit).
//
// Inputs:
//   theme_tokens.json sha256: 3637b188b1b39cb7514f967e29e67177a2d921414b2413da49a76b4813f489d7
// Upstream Java sources (paths + sha256 recorded in theme_tokens.json meta):
//   Theme.java: 12edf137d084f44989269d8f5914d17055cc885b307db5e9de8ab5acdf1a84ef
//   ThemeColors.java: 357f9eaf6b0eccd1924344bd60f33e3a0cdedced88025de2edf0e50f2350c362
//   bluebubbles.attheme: b1829c34447c8b0db06477c99d8c41f15a50c0db8b2fa8d3e4f693c29e88f69b
//   darkblue.attheme: 6922327115c412ef24cacc21af0546cd23dccab6e1f94e320a51332eed344bc0
//   arctic.attheme: 7e2ea3968b982b49b3eb5b9e030d88ba30806a1cb23c477e6e7b94397e1c6c74
//   day.attheme: a90cad2c5914a181db8500f63f39303782157694098a2ed81744345a334152d3
//   night.attheme: 8f0ab17a18ec6bdcba4907bf869acfcd985ebce350d6854befbbb2089fd57978
//
// Output is dartfmt-clean by construction: `dart format` must be a no-op
// on this file (enforced in CI with `dart format --set-exit-if-changed`).

/// Sparse color overlay for the bundled Android theme 'Blue'
/// (bluebubbles.attheme, 183 entries), parsed with Android-exact
/// `.attheme` semantics. Keys not present resolve through kFallbackKeys
/// and then kDefaultColors. Ordinal 0 (wallpaperFileOffset) mirrors
/// Android's parser, which always stores the wallpaper byte offset
/// (-1 when the file has no WPS marker) — it is not a color.
const Map<int, int> kBlueTheme = <int, int>{
  0: 0xFFFFFFFF, // wallpaperFileOffset
  4: 0xFF2981C4, // dialogTextLink
  6: 0xFF2294D9, // dialogTextBlue
  7: 0xFF2294D9, // dialogTextBlue2
  8: 0xFF169FE8, // dialogTextBlue4
  9: 0xFF8C8F91, // dialogTextGray
  10: 0xFF8C8F91, // dialogTextGray2
  11: 0xFF8C8F91, // dialogTextGray3
  12: 0xFF8C8F91, // dialogTextGray4
  25: 0xFF479DDF, // dialogLineProgress
  26: 0xFFE0EFF5, // dialogLineProgressBackground
  27: 0xFF3691D9, // dialogButton
  31: 0xFF326A98, // dialogTopBackground
  53: 0xFF24A6EC, // progressCircle
  54: 0x0D000000, // listSelector
  59: 0xFF077FC8, // windowBackgroundWhiteBlueText
  70: 0xFF8C8F91, // windowBackgroundWhiteGrayText
  71: 0xFF8C8F91, // windowBackgroundWhiteGrayText2
  72: 0xFF8C8F91, // windowBackgroundWhiteGrayText3
  73: 0xFF8C8F91, // windowBackgroundWhiteGrayText4
  75: 0xFF7B7E80, // windowBackgroundWhiteGrayText6
  80: 0xFF3994D3, // windowBackgroundWhiteValueText
  81: 0xFF298ACF, // windowBackgroundWhiteLinkText
  83: 0xFF2492D6, // windowBackgroundWhiteBlueHeader
  85: 0xFF229AF0, // switchTrackChecked
  100: 0xFF8C8F91, // emptyListPlaceholder
  102: 0xFFF6F6F6, // graySection
  103: 0xFF898C8E, // graySectionText
  120: 0xFF43AAEB, // inappPlayerPlayPause
  126: 0xFF3D9FE7, // contextProgressOuter1
  134: 0xFF69BDF9, // avatar_backgroundSaved
  136: 0xFFB3BBC1, // avatar_backgroundArchived
  137: 0xFF5AB5F4, // avatar_backgroundArchivedHidden
  155: 0xFFF2F2F2, // avatar_actionBarSelectorBlue
  160: 0xFF806DCF, // avatar_nameInMessageViolet
  162: 0xFF2FA3C9, // avatar_nameInMessageCyan
  163: 0xFF208DD6, // avatar_nameInMessageBlue
  164: 0xFFD26895, // avatar_nameInMessagePink
  165: 0xFFFFFFFF, // actionBarDefault
  166: 0xFFF2F2F2, // actionBarDefaultSelector
  167: 0xFFF2F2F2, // actionBarWhiteSelector
  174: 0xFF838C96, // actionBarDefaultSubtitle
  184: 0xFFF2F2F2, // actionBarTabSelector
  185: 0xFFFFFFFF, // actionBarDefaultArchived
  186: 0xFF5A6870, // actionBarDefaultArchivedSelector
  192: 0xFF36B0F4, // chats_onlineCircle
  193: 0xFF229AF0, // chats_unreadCounter
  209: 0xFF1D80C2, // chats_nameMessage
  210: 0xFF919191, // chats_nameMessageArchived
  211: 0xFF1D80C1, // chats_nameMessage_threeLines
  213: 0xFF1D80C2, // chats_attachMessage
  214: 0xFF1D7FBF, // chats_actionMessage
  219: 0xFF0F9DE6, // chats_sentCheck
  220: 0xFF0F9CE6, // chats_sentReadCheck
  221: 0xFFB8BCBF, // chats_sentClock
  224: 0xFF32A1E5, // chats_verifiedBackground
  228: 0x4D194971, // chats_menuTopShadow
  231: 0xFF3F3F3F, // chats_menuItemText
  233: 0xFF8E9499, // chats_menuItemIcon
  236: 0xFFD7ECF9, // chats_menuPhoneCats
  237: 0xFF5994C2, // chats_menuTopBackgroundCats
  240: 0xFF61AADF, // chats_actionBackground
  241: 0xFF559BD4, // chats_actionPressedBackground
  263: 0xFFDFA000, // chat_attachContactText
  266: 0xFF229AF0, // chat_status
  276: 0xFFE6F2FC, // chat_outBubble
  277: 0xFFD6F2FF, // chat_outBubbleSelected
  278: 0xFF01304A, // chat_outBubbleShadow
  283: 0xFF1B9BE6, // chat_outSentCheck
  284: 0xFF1B99E2, // chat_outSentCheckSelected
  285: 0xFF1B9BE6, // chat_outSentCheckRead
  287: 0xDC8CAABD, // chat_outSentClock
  288: 0xF07BA3CA, // chat_outSentClockSelected
  289: 0xFFFFFFFF, // chat_outMediaIcon
  291: 0xF08CAABD, // chat_outViews
  292: 0xF07BA3CA, // chat_outViewsSelected
  293: 0xFFA8C4D6, // chat_outMenu
  294: 0xFF94C6F1, // chat_outMenuSelected
  295: 0xFF0892D6, // chat_outInstant
  296: 0xFF1E9CDF, // chat_outInstantSelected
  297: 0xFF2284CA, // chat_outPreviewInstantText
  298: 0xFF2284CA, // chat_outForwardedNameText
  299: 0xFF2284CA, // chat_outViaBotNameText
  300: 0xFF379AE3, // chat_outReplyLine
  302: 0xFF2489CE, // chat_outReplyNameText
  304: 0xFF8CAABD, // chat_outReplyMediaMessageText
  305: 0xFF7BA3CB, // chat_outReplyMediaMessageSelectedText
  306: 0xFF43A6E7, // chat_outPreviewLine
  307: 0xFF2282C9, // chat_outSiteNameText
  308: 0xFF1E2F3E, // chat_outContactNameText
  309: 0xFF7C96A7, // chat_outContactPhoneText
  310: 0xFF6B98BC, // chat_outContactPhoneSelectedText
  313: 0xFF7BA3CA, // chat_outTimeSelectedText
  316: 0xFFA0CAEF, // chat_outAudioProgress
  317: 0xFF8DC9F5, // chat_outAudioSelectedProgress
  318: 0xF78CAABD, // chat_outTimeText
  319: 0xFF182C38, // chat_outAudioTitleText
  320: 0xFF8CAABD, // chat_outAudioDurationText
  321: 0xFF7BA3CA, // chat_outAudioDurationSelectedText
  322: 0x89A7CCE7, // chat_outAudioSeekbar
  323: 0xC2A7CCE7, // chat_outAudioCacheSeekbar
  324: 0x4753ABDD, // chat_outAudioSeekbarSelected
  325: 0xFF45A9F2, // chat_outAudioSeekbarFill
  326: 0xBDA4C4DF, // chat_outVoiceSeekbar
  327: 0x796AABD3, // chat_outVoiceSeekbarSelected
  328: 0xFF45A9F2, // chat_outVoiceSeekbarFill
  329: 0xFFFFFFFF, // chat_outFileProgress
  330: 0xFFD1F1FF, // chat_outFileProgressSelected
  331: 0xFF1E2F3E, // chat_outFileNameText
  332: 0xFF86A2B4, // chat_outFileInfoText
  333: 0xFF7BA3CA, // chat_outFileInfoSelectedText
  334: 0xB2C7E2F7, // chat_outFileBackground
  335: 0xFFBBE5FC, // chat_outFileBackgroundSelected
  336: 0xFF829EAF, // chat_outVenueInfoText
  337: 0xFF7BA3CA, // chat_outVenueInfoSelectedText
  339: 0xF044A9F2, // chat_outLoader
  340: 0xFF44A9F2, // chat_outLoaderSelected
  341: 0x827CA0C1, // chat_outLocationIcon
  342: 0xFF44A9F2, // chat_outContactBackground
  343: 0xFFFFFFFF, // chat_outContactIcon
  352: 0xFFE8F5FC, // chat_inBubbleSelected
  355: 0xFF0A79BD, // chat_messageLinkIn
  356: 0xFF097BC3, // chat_messageLinkOut
  366: 0xFF89B4C1, // chat_inSentClockSelected
  373: 0xFF89B4C1, // chat_inViewsSelected
  378: 0xFF1F95E2, // chat_inInstant
  379: 0xFF1F95E2, // chat_inInstantSelected
  382: 0x32077AC4, // chat_selectedBackground
  385: 0xFF2391DF, // chat_inPreviewInstantText
  389: 0xFF087ECA, // chat_inForwardedNameText
  391: 0xFF328ACF, // chat_inViaBotNameText
  393: 0xEB359DE6, // chat_inQuote
  395: 0xEB359DE6, // chat_inReplyLine
  397: 0xFF208DD6, // chat_inReplyNameText
  403: 0xEB37A3EF, // chat_inPreviewLine
  404: 0xFF1585D0, // chat_inSiteNameText
  405: 0xFF112335, // chat_inContactNameText
  406: 0xFFA1AAB3, // chat_inContactPhoneText
  407: 0xFF89B4C1, // chat_inContactPhoneSelectedText
  412: 0xE6A1AAB3, // chat_inAdminText
  418: 0xFF1A2E3B, // chat_inAudioTitleText
  424: 0xFF5EABE8, // chat_inAudioSeekbarFill
  427: 0xFF50AFE8, // chat_inVoiceSeekbarFill
  428: 0xFFFFFFFF, // chat_inFileProgress
  430: 0xFF298ACF, // chat_inFileNameText
  440: 0xFF5390D1, // chat_wallpaper
  441: 0xFFABC8E0, // chat_wallpaper_gradient_to1
  457: 0xFF49A8E4, // chat_topPanelLine
  458: 0xFF3696E0, // chat_topPanelTitle
  460: 0xFF2D96DF, // chat_addContact
  461: 0xE644A9F2, // chat_inLoader
  462: 0xFF44A9F2, // chat_inLoaderSelected
  470: 0xE644A9F2, // chat_inContactBackground
  472: 0xFF229AF0, // chat_replyPanelIcons
  474: 0xFF298ACF, // chat_replyPanelName
  476: 0xFF3A97E4, // chat_searchPanelIcons
  477: 0xFF3F99E0, // chat_searchPanelText
  483: 0xFF4393DD, // chat_unreadMessagesStartText
  507: 0xFF61B0EA, // chat_messagePanelVoiceBackground
  527: 0xFF000000, // chat_BlurAlpha
  593: 0xFFF7F7F7, // table_background
  594: 0xFFE0E0E0, // table_border
  602: 0xFFE5E5E5, // profile_actionPressedBackground
  620: 0xFF4299DB, // featuredStickers_addButtonPressed
  659: 0xFF41A2EF, // calls_callReceivedGreenIcon
  683: 0x14000000, // statisticChartActiveLine
  689: 0xFF327FE5, // statisticChartLine_blue
  690: 0xFF61C752, // statisticChartLine_green
  691: 0xFFE05356, // statisticChartLine_red
  692: 0xFFE3B727, // statisticChartLine_golden
  693: 0xFF58A8ED, // statisticChartLine_lightblue
  694: 0xFF8FCF39, // statisticChartLine_lightgreen
  695: 0xFFF28C39, // statisticChartLine_orange
  696: 0xFF7F79F3, // statisticChartLine_indigo
  700: 0xFF58A8ED, // color_lightblue
  701: 0xFF327FE5, // color_blue
  702: 0xFF61C752, // color_green
  703: 0xFF8FCF39, // color_lightgreen
  704: 0xFFE05356, // color_red
  705: 0xFFF28C39, // color_orange
  706: 0xFFE3B727, // color_yellow
  707: 0xFF7F79F3, // color_purple
  775: 0xFF229AF0, // telegram_color
};
