// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by flutter/tool/emit_dart.py from flutter/tool/theme_tokens.json
// (token codegen pipeline stages 2-3, flutter/docs/ARCHITECTURE.md section 4.3).
// Regenerate: python3 flutter/tool/gen_tokens.py && python3 flutter/tool/emit_dart.py
// Drift gate:  both scripts support --check (byte-compare, nonzero exit).
//
// Inputs:
//   theme_tokens.json sha256: 3637b188b1b39cb7514f967e29e67177a2d921414b2413da49a76b4813f489d7
// Upstream Java sources (paths + sha256 recorded in theme_tokens.json meta):
//   Theme.java: 12edf137d084f44989269d8f5914d17055cc885b307db5e9de8ab5acdf1a84ef
//   ThemeColors.java: 357f9eaf6b0eccd1924344bd60f33e3a0cdedced88025de2edf0e50f2350c362
//   bluebubbles.attheme: b1829c34447c8b0db06477c99d8c41f15a50c0db8b2fa8d3e4f693c29e88f69b
//   darkblue.attheme: 6922327115c412ef24cacc21af0546cd23dccab6e1f94e320a51332eed344bc0
//   arctic.attheme: 7e2ea3968b982b49b3eb5b9e030d88ba30806a1cb23c477e6e7b94397e1c6c74
//   day.attheme: a90cad2c5914a181db8500f63f39303782157694098a2ed81744345a334152d3
//   night.attheme: 8f0ab17a18ec6bdcba4907bf869acfcd985ebce350d6854befbbb2089fd57978
//
// Output is dartfmt-clean by construction: `dart format` must be a no-op
// on this file (enforced in CI with `dart format --set-exit-if-changed`).

/// Sparse color overlay for the bundled Android theme 'Arctic Blue'
/// (arctic.attheme, 278 entries), parsed with Android-exact
/// `.attheme` semantics. Keys not present resolve through kFallbackKeys
/// and then kDefaultColors. Ordinal 0 (wallpaperFileOffset) mirrors
/// Android's parser, which always stores the wallpaper byte offset
/// (-1 when the file has no WPS marker) — it is not a color.
///
/// Android parity note: the asset's final line has no trailing newline
/// and is silently dropped by Theme.getThemeFileValues — replicated here
/// (dropped: `chat_editMediaButton=-15033089`).
const Map<int, int> kArcticBlueTheme = <int, int>{
  0: 0xFFFFFFFF, // wallpaperFileOffset
  4: 0xFF2589EB, // dialogTextLink
  6: 0xFF1F8DD6, // dialogTextBlue
  7: 0xFF1E95DB, // dialogTextBlue2
  8: 0xFF1191E8, // dialogTextBlue4
  9: 0xFF329ADD, // dialogTextGray
  16: 0xFF2491EF, // dialogCheckboxSquareBackground
  21: 0xFF2FAAF5, // dialogRoundCheckBox
  24: 0xFF259EF0, // dialogRadioBackgroundChecked
  25: 0xFF229CE7, // dialogLineProgress
  26: 0xFFCFE6FB, // dialogLineProgressBackground
  27: 0xFF2A90EC, // dialogButton
  52: 0xFFFFFFFF, // windowBackgroundCheckText
  53: 0xFF3FA5FE, // progressCircle
  54: 0x0F000000, // listSelector
  59: 0xFF2187EF, // windowBackgroundWhiteBlueText
  61: 0xFF318ADA, // windowBackgroundWhiteBlueText3
  62: 0xFF3E96E8, // windowBackgroundWhiteBlueText4
  63: 0xFF3A9CF1, // windowBackgroundWhiteBlueText5
  65: 0xFF469DE1, // windowBackgroundWhiteBlueText7
  66: 0xFF2298F8, // windowBackgroundWhiteBlueButton
  67: 0xFF469DF8, // windowBackgroundWhiteBlueIcon
  69: 0xFF04AC35, // windowBackgroundWhiteGreenText2
  70: 0xFF8B949F, // windowBackgroundWhiteGrayText
  78: 0xFF333333, // windowBackgroundWhiteBlackText
  80: 0xFF3795EB, // windowBackgroundWhiteValueText
  81: 0xFF298ACF, // windowBackgroundWhiteLinkText
  82: 0x2162A9E3, // windowBackgroundWhiteLinkSelection
  83: 0xFF2D95ED, // windowBackgroundWhiteBlueHeader
  85: 0xFF229AF0, // switchTrackChecked
  87: 0xFF0084CB, // switchTrackBlueChecked
  92: 0xFFF57480, // switch2Track
  93: 0xFF50A7ED, // switch2TrackChecked
  101: 0xFFE6E6E6, // divider
  102: 0xFFF8F8F8, // graySection
  103: 0xFF838A93, // graySectionText
  105: 0xFF20A2FF, // radioBackgroundChecked
  109: 0xFF229AF0, // fastScrollActive
  114: 0xFFE6555E, // text_RedBold
  120: 0xFF1E9DF5, // inappPlayerPlayPause
  121: 0xFF8C959A, // inappPlayerClose
  122: 0xFF2C9AF1, // returnToCallBackground
  126: 0xFF28A0FE, // contextProgressOuter1
  127: 0xCEC3DDF6, // contextProgressInner2
  128: 0xFF45A2FF, // contextProgressOuter2
  134: 0xFF45B6FF, // avatar_backgroundSaved
  143: 0xFF50A5E6, // avatar_backgroundBlue
  153: 0xFF3496EC, // avatar_backgroundInProfileBlue
  154: 0xFFFFFFFF, // avatar_backgroundActionBarBlue
  155: 0x0F353A42, // avatar_actionBarSelectorBlue
  156: 0xFF424952, // avatar_actionBarIconBlue
  157: 0xFF8D8D8D, // avatar_subtitleInProfileBlue
  160: 0xFF836FE6, // avatar_nameInMessageViolet
  163: 0xFF328AE5, // avatar_nameInMessageBlue
  164: 0xFFCB4F86, // avatar_nameInMessagePink
  165: 0xFFFFFFFF, // actionBarDefault
  166: 0x102A2F35, // actionBarDefaultSelector
  167: 0x10000000, // actionBarWhiteSelector
  168: 0xFF404E56, // actionBarDefaultIcon
  173: 0xFF333333, // actionBarDefaultTitle
  174: 0xFF8B929A, // actionBarDefaultSubtitle
  175: 0xFF000000, // actionBarDefaultSearch
  176: 0x887B7B7B, // actionBarDefaultSearchPlaceholder
  181: 0xFF309EED, // actionBarTabActiveText
  182: 0xFF8B929A, // actionBarTabUnactiveText
  183: 0xFF2FA2F7, // actionBarTabLine
  184: 0x082A2F35, // actionBarTabSelector
  185: 0xFFFFFFFF, // actionBarDefaultArchived
  187: 0xFF2D3035, // actionBarDefaultArchivedIcon
  188: 0xFF33383C, // actionBarDefaultArchivedTitle
  192: 0xFF4BCB1C, // chats_onlineCircle
  193: 0xFF0BABFF, // chats_unreadCounter
  198: 0xFF00A60E, // chats_secretName
  199: 0xFF19B126, // chats_secretIcon
  201: 0xFF53A6F3, // chats_archiveBackground
  202: 0xFFBBC2CF, // chats_archivePinBackground
  208: 0xFAE32246, // chats_draft
  209: 0xFF3588D4, // chats_nameMessage
  210: 0xFF919191, // chats_nameMessageArchived
  211: 0xFF424449, // chats_nameMessage_threeLines
  212: 0xFF919191, // chats_nameMessageArchived_threeLines
  213: 0xFF3588D4, // chats_attachMessage
  214: 0xFF3588D4, // chats_actionMessage
  217: 0x06000000, // chats_pinnedOverlay
  219: 0xFF2AA4F6, // chats_sentCheck
  221: 0x7B2E96FE, // chats_sentClock
  222: 0xFFFF0000, // chats_sentError
  224: 0xFF39A9F8, // chats_verifiedBackground
  228: 0x29175284, // chats_menuTopShadow
  229: 0x002C9EFF, // chats_menuTopShadowCats
  230: 0xFFFFFFFF, // chats_menuBackground
  234: 0xFFFFFFFF, // chats_menuName
  235: 0xC3FFFFFF, // chats_menuPhone
  236: 0xFFFFFFFF, // chats_menuPhoneCats
  237: 0xFF5393CF, // chats_menuTopBackgroundCats
  240: 0xFF50A4F5, // chats_actionBackground
  241: 0xFF3283D8, // chats_actionPressedBackground
  244: 0xFF66ADE1, // chats_tabUnreadActiveBackground
  245: 0xFF2FA2F7, // chats_tabUnreadUnactiveBackground
  263: 0xFFDFA000, // chat_attachContactText
  266: 0xFF048FE2, // chat_status
  268: 0xFFFFFFFF, // chat_inBubble
  270: 0x761D3753, // chat_inBubbleShadow
  276: 0xFF3490EB, // chat_outBubble
  277: 0xFF3490E1, // chat_outBubbleSelected
  278: 0x000D4073, // chat_outBubbleShadow
  282: 0xFFB7E7FF, // chat_outGreenCall
  283: 0xC8FFFFFF, // chat_outSentCheck
  284: 0xB8FFFFFF, // chat_outSentCheckSelected
  285: 0xC7FFFFFF, // chat_outSentCheckRead
  287: 0x70FFFFFF, // chat_outSentClock
  288: 0x70FFFFFF, // chat_outSentClockSelected
  289: 0xFF3490E1, // chat_outMediaIcon
  290: 0xFF3490E1, // chat_outMediaIconSelected
  291: 0xB4FFFFFF, // chat_outViews
  292: 0xB4FFFFFF, // chat_outViewsSelected
  293: 0x90FFFFFF, // chat_outMenu
  294: 0x90FFFFFF, // chat_outMenuSelected
  295: 0xFFFFFFFF, // chat_outInstant
  296: 0xFFFFFFFF, // chat_outInstantSelected
  297: 0xFFFFFFFF, // chat_outPreviewInstantText
  298: 0xFFFFFFFF, // chat_outForwardedNameText
  299: 0xFFFFFFFF, // chat_outViaBotNameText
  300: 0xFFFFFFFF, // chat_outReplyLine
  302: 0xFFFFFFFF, // chat_outReplyNameText
  303: 0xFFFFFFFF, // chat_outReplyMessageText
  304: 0xC0FFFFFF, // chat_outReplyMediaMessageText
  305: 0xC0FFFFFF, // chat_outReplyMediaMessageSelectedText
  306: 0xFFFFFFFF, // chat_outPreviewLine
  307: 0xFFFFFFFF, // chat_outSiteNameText
  308: 0xFFFFFFFF, // chat_outContactNameText
  309: 0xC0FFFFFF, // chat_outContactPhoneText
  310: 0xC0FFFFFF, // chat_outContactPhoneSelectedText
  311: 0xFFFFFFFF, // chat_outAudioPerformerText
  312: 0xFFFFFFFF, // chat_outAudioPerformerSelectedText
  313: 0xC0FFFFFF, // chat_outTimeSelectedText
  316: 0xFF598EDE, // chat_outAudioProgress
  317: 0xFF598EDE, // chat_outAudioSelectedProgress
  318: 0xC0FFFFFF, // chat_outTimeText
  319: 0xFFFFFFFF, // chat_outAudioTitleText
  320: 0xC0FFFFFF, // chat_outAudioDurationText
  321: 0xC0FFFFFF, // chat_outAudioDurationSelectedText
  322: 0x58A7D4FF, // chat_outAudioSeekbar
  323: 0x2BFFFFFF, // chat_outAudioCacheSeekbar
  324: 0x58A7D4FF, // chat_outAudioSeekbarSelected
  325: 0xFFFFFFFF, // chat_outAudioSeekbarFill
  326: 0x70FFFFFF, // chat_outVoiceSeekbar
  327: 0x70FFFFFF, // chat_outVoiceSeekbarSelected
  328: 0xFFFFFFFF, // chat_outVoiceSeekbarFill
  329: 0xFF3490E1, // chat_outFileProgress
  330: 0xFF3490E1, // chat_outFileProgressSelected
  331: 0xFFFFFFFF, // chat_outFileNameText
  332: 0xC0FFFFFF, // chat_outFileInfoText
  333: 0xC0FFFFFF, // chat_outFileInfoSelectedText
  334: 0x508AC4F5, // chat_outFileBackground
  335: 0x508AC4F5, // chat_outFileBackgroundSelected
  336: 0xC0FFFFFF, // chat_outVenueInfoText
  337: 0xC0FFFFFF, // chat_outVenueInfoSelectedText
  339: 0xFFFFFFFF, // chat_outLoader
  340: 0xFFFFFFFF, // chat_outLoaderSelected
  341: 0xE4FFFFFF, // chat_outLocationIcon
  342: 0xFFFFFFFF, // chat_outContactBackground
  343: 0xFF3490E1, // chat_outContactIcon
  345: 0x6B73BFED, // chat_outTextSelectionHighlight
  352: 0xFFE5F4FF, // chat_inBubbleSelected
  354: 0xFFFFFFFF, // chat_messageTextOut
  355: 0xFF0183E8, // chat_messageLinkIn
  356: 0xFFE6F7FF, // chat_messageLinkOut
  357: 0xFFFFFFFF, // chat_serviceText
  358: 0xFFFFFFFF, // chat_serviceLink
  359: 0xFFFFFFFF, // chat_serviceIcon
  360: 0x55547897, // chat_serviceBackground
  361: 0x75547897, // chat_serviceBackgroundSelected
  363: 0x66737373, // chat_muteIcon
  364: 0xFF737373, // chat_lockIcon
  365: 0xFFB0BAC4, // chat_inSentClock
  366: 0xFF8DBCD9, // chat_inSentClockSelected
  369: 0xFFFFFFFF, // chat_inMediaIcon
  373: 0xFF9EBECA, // chat_inViewsSelected
  376: 0xFFA2C3CD, // chat_inMenuSelected
  378: 0xFF259EF0, // chat_inInstant
  379: 0xFF328AE5, // chat_inInstantSelected
  380: 0xFFFF0000, // chat_sentError
  382: 0x2D13A1FF, // chat_selectedBackground
  385: 0xFF168CDE, // chat_inPreviewInstantText
  389: 0xFF328AE5, // chat_inForwardedNameText
  391: 0xFF328AE5, // chat_inViaBotNameText
  393: 0xFF4197E9, // chat_inQuote
  395: 0xFF4197E9, // chat_inReplyLine
  397: 0xFF328AE5, // chat_inReplyNameText
  401: 0xFF93ACBC, // chat_inReplyMediaMessageSelectedText
  403: 0xFF3D9DF4, // chat_inPreviewLine
  404: 0xFF328AE5, // chat_inSiteNameText
  405: 0xFF323232, // chat_inContactNameText
  406: 0xFFA1AAB3, // chat_inContactPhoneText
  407: 0xFF93ACBC, // chat_inContactPhoneSelectedText
  410: 0xFFE0F4FE, // chat_inAudioSelectedProgress
  413: 0xFF98B2CA, // chat_inAdminSelectedText
  415: 0xFF93ACBC, // chat_inTimeSelectedText
  418: 0xFF292C30, // chat_inAudioTitleText
  420: 0xFF93ACBC, // chat_inAudioDurationSelectedText
  422: 0x3FD8E5F0, // chat_inAudioCacheSeekbar
  424: 0xFF51A3E8, // chat_inAudioSeekbarFill
  425: 0xFFCBD2DA, // chat_inVoiceSeekbar
  426: 0xFFB8D6E8, // chat_inVoiceSeekbarSelected
  427: 0xFF379BEF, // chat_inVoiceSeekbarFill
  428: 0xFFFFFFFF, // chat_inFileProgress
  430: 0xFF298ACF, // chat_inFileNameText
  431: 0xFFA1AAB3, // chat_inFileInfoText
  432: 0xFF93ACBC, // chat_inFileInfoSelectedText
  433: 0xFFEBF3FC, // chat_inFileBackground
  434: 0xFFD4EBFC, // chat_inFileBackgroundSelected
  435: 0xFFA1AAB3, // chat_inVenueInfoText
  436: 0xFF93ACBC, // chat_inVenueInfoSelectedText
  438: 0x2244A1EA, // chat_linkSelectBackground
  439: 0x3D3AA2ED, // chat_textSelectBackground
  440: 0xFFD8E4F3, // chat_wallpaper
  446: 0xE5000000, // chat_messagePanelShadow
  451: 0xFF229AF0, // chat_messagePanelSend
  457: 0xEA47A1FE, // chat_topPanelLine
  458: 0xEF328AE5, // chat_topPanelTitle
  459: 0xFF808689, // chat_topPanelMessage
  460: 0xFF1E8AE5, // chat_addContact
  461: 0xFF48A7F6, // chat_inLoader
  462: 0xFF339EED, // chat_inLoaderSelected
  470: 0xFF33A1F7, // chat_inContactBackground
  472: 0xFF229AF0, // chat_replyPanelIcons
  474: 0xFF298ACF, // chat_replyPanelName
  479: 0xFF148DFE, // chat_fieldOverlayText
  481: 0xFF328AE5, // chat_botSwitchToInlineText
  483: 0xFF228DE1, // chat_unreadMessagesStartText
  485: 0xFF349EF5, // chat_inlineResultIcon
  505: 0xFF349AF0, // chat_emojiPanelNewTrending
  507: 0xFF2991E7, // chat_messagePanelVoiceBackground
  513: 0xFFF34646, // chat_recordedVoiceDot
  514: 0xFF3E97EB, // chat_recordedVoiceBackground
  523: 0xFF329EEB, // chat_goDownButtonCounterBackground
  524: 0x281E96ED, // chat_inTextSelectionHighlight
  525: 0xFF51ABF1, // chat_TextSelectionCursor
  527: 0xCC000000, // chat_BlurAlpha
  528: 0xC1000000, // chat_BlurAlphaSlow
  598: 0xFF118DFE, // profile_creatorIcon
  599: 0xFF363636, // profile_title
  600: 0xFFFFFFFF, // profile_actionIcon
  601: 0xFF42A8F6, // profile_actionBackground
  602: 0xFF2B87E8, // profile_actionPressedBackground
  603: 0xFF45A8F4, // profile_verifiedBackground
  604: 0xFFFFFFFF, // profile_verifiedCheck
  605: 0xFF1A97E6, // profile_status
  613: 0xFFF4F4F4, // sharedMedia_linkPlaceholder
  616: 0xFF34AAFF, // featuredStickers_addedIcon
  620: 0xFF4196D6, // featuredStickers_addButtonPressed
  628: 0xFF329FED, // groupcreate_cursor
  638: 0xFF279EF5, // picker_enabledButton
  640: 0xFF35A3F7, // picker_badge
  642: 0xFF50A4F5, // location_sendLocationBackground
  653: 0x143198E8, // location_actionPressedBackground
  659: 0xFF2FC766, // calls_callReceivedGreenIcon
  674: 0xFF9CA4B0, // player_time
  677: 0xFF23A3FE, // player_progress
  679: 0xFF2CA3FE, // player_buttonActive
  683: 0x14000000, // statisticChartActiveLine
  689: 0xFF327FE5, // statisticChartLine_blue
  690: 0xFF61C752, // statisticChartLine_green
  691: 0xFFE05356, // statisticChartLine_red
  692: 0xFFE3B727, // statisticChartLine_golden
  693: 0xFF58A8ED, // statisticChartLine_lightblue
  694: 0xFF8FCF39, // statisticChartLine_lightgreen
  695: 0xFFF28C39, // statisticChartLine_orange
  696: 0xFF7F79F3, // statisticChartLine_indigo
  700: 0xFF58A8ED, // color_lightblue
  701: 0xFF327FE5, // color_blue
  702: 0xFF61C752, // color_green
  703: 0xFF8FCF39, // color_lightgreen
  704: 0xFFE05356, // color_red
  705: 0xFFF28C39, // color_orange
  706: 0xFFE3B727, // color_yellow
  707: 0xFF7F79F3, // color_purple
};
