// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by flutter/tool/extract_metrics.py from
// flutter/tool/extract_spec.yaml — the scalar constants of the
// liquid-glass system (ARCHITECTURE.md §3.4) extracted from the
// Telegram Android sources under TMessagesProj/src/main/.
// Regenerate: python3 flutter/tool/extract_metrics.py
// Verify:     python3 flutter/tool/extract_metrics.py --check
//
// Values suffixed `Dp` are logical dp: multiply by the device pixel
// ratio at runtime (dp()/dpf2() rounding semantics live in
// foundation/dimens.dart).
//
// Spec SHA-256: 50ff1492b796fedd077ca9491329b2e4abfa7d1de6f75215fac4186e9a0ab950

/// Default lens thickness in dp when liquidThickness <= 0 (dp(11) at draw time).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawableRenderNode.java`.
const double kGlassThicknessDefaultDp = 11.0;

/// Thickness is clamped to min(width, height) / this divisor (Java int division).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawableRenderNode.java`.
const int kGlassThicknessBoundsDivisor = 5;

/// Absolute thickness floor in physical px after clamping.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawableRenderNode.java`.
const int kGlassThicknessMinPx = 1;

/// Default refraction displacement multiplier (Props.liquidIntensity).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawable.java`.
const double kGlassRefractIntensityDefault = 0.75;

/// Index of refraction (Props.liquidIndex) — no production setter exists, always 1.5.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawable.java`.
const double kGlassRefractIndex = 1.5;

/// Themed tint alpha when the liquid-glass LiteMode flag is enabled.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const double kGlassTintAlphaLiquid = 0.85;

/// Themed tint alpha in frosted (non-liquid) mode.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const double kGlassTintAlphaFrosted = 0.76;

/// Perceived brightness below this value selects the dark stroke/shadow set.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const double kGlassDarkBrightnessThreshold = 0.721;

/// Top hairline stroke color, dark themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const int kGlassStrokeTopColorDark = 0x28FFFFFF;

/// Bottom hairline stroke color, dark themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const int kGlassStrokeBottomColorDark = 0x14FFFFFF;

/// Drop shadow color, dark themes (0 = no shadow).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const int kGlassShadowColorDark = 0x00000000;

/// Top hairline stroke color, light themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const int kGlassStrokeTopColorLight = 0xFFFFFFFF;

/// Bottom hairline stroke color, light themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const int kGlassStrokeBottomColorLight = 0xFFFFFFFF;

/// Drop shadow color, light themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/BlurredBackgroundColorProviderThemed.java`.
const int kGlassShadowColorLight = 0x20000000;

/// Default top stroke width in dp (dpf2 exact-float semantics).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawable.java`.
const double kGlassStrokeWidthTopDp = 1.0;

/// Default bottom stroke width in dp (2/3 dp).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawable.java`.
const double kGlassStrokeWidthBottomDp = 0.6666666666666666;

/// Default shadow blur radius in dp.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawable.java`.
const double kGlassShadowRadiusDp = 1.0;

/// Default shadow x offset in dp.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawable.java`.
const double kGlassShadowDxDp = 0.0;

/// Default shadow y offset in dp (1/3 dp).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/BlurredBackgroundDrawable.java`.
const double kGlassShadowDyDp = 0.3333333333333333;

/// Glass chain downscale factor (4x per axis).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/DownscaleScrollableNoiseSuppressor.java`.
const int kGlassBackdropDownscale = 4;

/// Glass chain blur radius in dp (dpf2), paired with the saturation matrix.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/DownscaleScrollableNoiseSuppressor.java`.
const double kGlassBackdropBlurRadiusDp = 6.0;

/// Frosted chain downscale factor (8x per axis), applied over the glass output.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/DownscaleScrollableNoiseSuppressor.java`.
const int kFrostedBackdropDownscale = 8;

/// Frosted chain blur radius in dp — the 40 - 1.66 = 38.34 expression, evaluated.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/DownscaleScrollableNoiseSuppressor.java`.
const double kFrostedBackdropBlurRadiusDp = 38.34;

/// Color-matrix saturation factor of the glass/frosted chains (x3).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/messenger/utils/RenderNodeEffects.java`.
const double kGlassBackdropSaturation = 3.0;

/// Default fade height in dp (opacity=false, 5-stop table).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/BlurredBackgroundWithFadeDrawable.java`.
const double kFadeDefaultHeightDp = 40.0;

/// MainTabs fade height in dp (opacity=true, 4-stop table).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/MainTabsActivity.java`.
const double kFadeMainTabsHeightDp = 60.0;

/// Evenly-spaced gradient alpha numerators, opacity=true (4 stops, over 285).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/BlurredBackgroundWithFadeDrawable.java`.
const List<int> kFadeStopAlphasOpacity = <int>[0x00, 0x60, 0xB0, 0xE8];

/// Alpha divisor for the opacity=true stop table — 285, so max is about 0.813 of the source alpha.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/BlurredBackgroundWithFadeDrawable.java`.
const int kFadeStopAlphaDivisorOpacity = 285;

/// Evenly-spaced gradient alpha numerators, opacity=false (5 stops, over 255).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/BlurredBackgroundWithFadeDrawable.java`.
const List<int> kFadeStopAlphasDefault = <int>[0x00, 0x60, 0xB0, 0xE8, 0xFF];

/// Alpha divisor for the opacity=false stop table (255).
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/BlurredBackgroundWithFadeDrawable.java`.
const int kFadeStopAlphaDivisorDefault = 255;

/// mainTabs solveSrcColor target alpha, liquid mode.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const double kMainTabsTintAlphaLiquid = 0.85;

/// mainTabs solveSrcColor target alpha, frosted mode.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const double kMainTabsTintAlphaFrosted = 0.76;

/// mainTabs top stroke color, light themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const int kMainTabsStrokeTopColorLight = 0x11000000;

/// mainTabs top stroke color, dark themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const int kMainTabsStrokeTopColorDark = 0x06FFFFFF;

/// mainTabs bottom stroke color, light themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const int kMainTabsStrokeBottomColorLight = 0x20000000;

/// mainTabs bottom stroke color, dark themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const int kMainTabsStrokeBottomColorDark = 0x11FFFFFF;

/// mainTabs shadow color, light themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const int kMainTabsShadowColorLight = 0x20000000;

/// mainTabs shadow color, dark themes.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const int kMainTabsShadowColorDark = 0x04FFFFFF;

/// mainTabs shadow blur radius in dp.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const double kMainTabsShadowRadiusDp = 2.667;

/// mainTabs shadow x offset in dp.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const double kMainTabsShadowDxDp = 0.0;

/// mainTabs shadow y offset in dp.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const double kMainTabsShadowDyDp = 0.85;

/// mainTabs top stroke width in dp.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const double kMainTabsStrokeWidthTopDp = 0.4;

/// mainTabs bottom stroke width in dp.
///
/// Source: `TMessagesProj/src/main/java/org/telegram/ui/Components/blur3/drawable/color/impl/BlurredBackgroundProviderImpl.java`.
const double kMainTabsStrokeWidthBottomDp = 0.4;
