// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by flutter/tool/gen_shader_bindings.py from
// flutter/telegram_ui/shaders/liquid_glass.frag.
// Regenerate: python3 flutter/tool/gen_shader_bindings.py
// Verify:     python3 flutter/tool/gen_shader_bindings.py --check
//
// Uniform layout SHA-256: 54d75a8c55b05cee04bb87021cdb2cff647b86765e87f87d276eb44594c1b482
//
// Float slot indices for ui.FragmentShader.setFloat, in shader
// declaration order. The first vec2 (u_size) is set by the engine
// when the shader runs as an ImageFilter; set it manually when
// driving the shader through a Canvas.

/// `u_size` component 0 — engine-set backdrop size in physical px (AGSL `resolution`).
const int kUniformSizeX = 0;

/// `u_size` component 1 — engine-set backdrop size in physical px (AGSL `resolution`).
const int kUniformSizeY = 1;

/// `u_center` component 0 — panel rect center in px (AGSL `center`).
const int kUniformCenterX = 2;

/// `u_center` component 1 — panel rect center in px (AGSL `center`).
const int kUniformCenterY = 3;

/// `u_half_size` component 0 — panel half extents in px (AGSL `size` — HALF width/height).
const int kUniformHalfSizeX = 4;

/// `u_half_size` component 1 — panel half extents in px (AGSL `size` — HALF width/height).
const int kUniformHalfSizeY = 5;

/// `u_radius` component 0 — corner radii packed (RB, RT, LB, LT) (AGSL `radius`).
const int kUniformRadiusRightBottom = 6;

/// `u_radius` component 1 — corner radii packed (RB, RT, LB, LT) (AGSL `radius`).
const int kUniformRadiusRightTop = 7;

/// `u_radius` component 2 — corner radii packed (RB, RT, LB, LT) (AGSL `radius`).
const int kUniformRadiusLeftBottom = 8;

/// `u_radius` component 3 — corner radii packed (RB, RT, LB, LT) (AGSL `radius`).
const int kUniformRadiusLeftTop = 9;

/// `u_thickness` component 0 — glass lip thickness in px (AGSL `thickness`).
const int kUniformThickness = 10;

/// `u_refract_index` component 0 — index of refraction, 1.5 in production (AGSL `refract_index`).
const int kUniformRefractIndex = 11;

/// `u_refract_intensity` component 0 — displacement multiplier, 0.75 default (AGSL `refract_intensity`).
const int kUniformRefractIntensity = 12;

/// `u_foreground_color` component 0 — premultiplied tint (AGSL `foreground_color_premultiplied`).
const int kUniformForegroundColorR = 13;

/// `u_foreground_color` component 1 — premultiplied tint (AGSL `foreground_color_premultiplied`).
const int kUniformForegroundColorG = 14;

/// `u_foreground_color` component 2 — premultiplied tint (AGSL `foreground_color_premultiplied`).
const int kUniformForegroundColorB = 15;

/// `u_foreground_color` component 3 — premultiplied tint (AGSL `foreground_color_premultiplied`).
const int kUniformForegroundColorA = 16;

/// Total float uniform count — bounds assert for the uniform packer.
const int kLiquidGlassUniformFloatCount = 17;

/// Sampler index of `u_backdrop` — backdrop texture, bound by the engine as the filter input (AGSL `img`).
const int kUniformBackdropSampler = 0;

/// Total sampler uniform count.
const int kLiquidGlassUniformSamplerCount = 1;
