// GENERATED CODE - DO NOT MODIFY BY HAND.
//
// Generated by flutter/tool/emit_dart.py from flutter/tool/theme_tokens.json
// (token codegen pipeline stages 2-3, flutter/docs/ARCHITECTURE.md section 4.3).
// Regenerate: python3 flutter/tool/gen_tokens.py && python3 flutter/tool/emit_dart.py
// Drift gate:  both scripts support --check (byte-compare, nonzero exit).
//
// Inputs:
//   theme_tokens.json sha256: 3637b188b1b39cb7514f967e29e67177a2d921414b2413da49a76b4813f489d7
// Upstream Java sources (paths + sha256 recorded in theme_tokens.json meta):
//   Theme.java: 12edf137d084f44989269d8f5914d17055cc885b307db5e9de8ab5acdf1a84ef
//   ThemeColors.java: 357f9eaf6b0eccd1924344bd60f33e3a0cdedced88025de2edf0e50f2350c362
//   bluebubbles.attheme: b1829c34447c8b0db06477c99d8c41f15a50c0db8b2fa8d3e4f693c29e88f69b
//   darkblue.attheme: 6922327115c412ef24cacc21af0546cd23dccab6e1f94e320a51332eed344bc0
//   arctic.attheme: 7e2ea3968b982b49b3eb5b9e030d88ba30806a1cb23c477e6e7b94397e1c6c74
//   day.attheme: a90cad2c5914a181db8500f63f39303782157694098a2ed81744345a334152d3
//   night.attheme: 8f0ab17a18ec6bdcba4907bf869acfcd985ebce350d6854befbbb2089fd57978
//
// Output is dartfmt-clean by construction: `dart format` must be a no-op
// on this file (enforced in CI with `dart format --set-exit-if-changed`).

/// Key -> fallback key (Theme.java `fallbackKeys` static table,
/// 183 entries). Resolved at lookup time — currentColors[key] ??
/// currentColors[fallback[key]] ?? defaults[key] — never flattened, so
/// sparse overrides keep fallback behavior (ARCHITECTURE.md section 4.1).
const Map<int, int> kFallbackKeys = <int, int>{
  32: 98, // dialog_inlineProgressBackground -> windowBackgroundGray
  33: 233, // dialog_inlineProgress -> chats_menuItemIcon
  34: 494, // dialogSearchBackground -> chat_emojiPanelStickerPackSelector
  35: 491, // dialogSearchHint -> chat_emojiPanelIcon
  36: 491, // dialogSearchIcon -> chat_emojiPanelIcon
  37: 78, // dialogSearchText -> windowBackgroundWhiteBlackText
  38: 21, // dialogFloatingButton -> dialogRoundCheckBox
  39: 21, // dialogFloatingButtonPressed -> dialogRoundCheckBox
  40: 22, // dialogFloatingIcon -> dialogRoundCheckBoxCheck
  41: 489, // dialogShadowLine -> chat_emojiPanelShadowLine
  42: 674, // dialogEmptyImage -> player_time
  43: 674, // dialogEmptyText -> player_time
  44: 138, // dialogSwipeRemove -> avatar_backgroundRed
  45: 587, // dialogReactionMentionBackground -> voipgroup_mutedByAdminGradient2
  47: 98, // dialogGiftsBackground -> windowBackgroundGray
  48: 71, // dialogGiftsTabText -> windowBackgroundWhiteGrayText2
  50: 49, // windowBackgroundUnchecked -> windowBackgroundWhite
  51: 49, // windowBackgroundChecked -> windowBackgroundWhite
  52: 49, // windowBackgroundCheckText -> windowBackgroundWhite
  55: 54, // settings_listSelector -> listSelector
  66: 80, // windowBackgroundWhiteBlueButton -> windowBackgroundWhiteValueText
  67: 80, // windowBackgroundWhiteBlueIcon -> windowBackgroundWhiteValueText
  86: 84, // switchTrackBlue -> switchTrack
  87: 85, // switchTrackBlueChecked -> switchTrackChecked
  88: 49, // switchTrackBlueThumb -> windowBackgroundWhite
  89: 49, // switchTrackBlueThumbChecked -> windowBackgroundWhite
  90: 54, // switchTrackBlueSelector -> listSelector
  91: 54, // switchTrackBlueSelectorChecked -> listSelector
  103: 71, // graySectionText -> windowBackgroundWhiteGrayText2
  107: 194, // checkboxDisabled -> chats_unreadCounterMuted
  112: 58, // pollCreateIcons -> windowBackgroundWhiteGrayIcon
  123: 49, // returnToCallMutedBackground -> windowBackgroundWhite
  131: 125, // contextProgressInner4 -> contextProgressInner1
  132: 126, // contextProgressOuter4 -> contextProgressOuter1
  135: 134, // avatar_background2Saved -> avatar_backgroundSaved
  136: 194, // avatar_backgroundArchived -> chats_unreadCounterMuted
  137: 134, // avatar_backgroundArchivedHidden -> avatar_backgroundSaved
  145: 138, // avatar_background2Red -> avatar_backgroundRed
  146: 139, // avatar_background2Orange -> avatar_backgroundOrange
  147: 140, // avatar_background2Violet -> avatar_backgroundViolet
  148: 141, // avatar_background2Green -> avatar_backgroundGreen
  149: 142, // avatar_background2Cyan -> avatar_backgroundCyan
  150: 143, // avatar_background2Blue -> avatar_backgroundBlue
  151: 144, // avatar_background2Pink -> avatar_backgroundPink
  173: 78, // actionBarDefaultTitle -> windowBackgroundWhiteBlackText
  178: 29, // actionBarDefaultSubmenuItemIcon -> dialogIcon
  180: 98, // actionBarDefaultSubmenuSeparator -> windowBackgroundGray
  181: 173, // actionBarTabActiveText -> actionBarDefaultTitle
  182: 174, // actionBarTabUnactiveText -> actionBarDefaultSubtitle
  183: 173, // actionBarTabLine -> actionBarDefaultTitle
  184: 166, // actionBarTabSelector -> actionBarDefaultSelector
  185: 165, // actionBarDefaultArchived -> actionBarDefault
  186: 166, // actionBarDefaultArchivedSelector -> actionBarDefaultSelector
  187: 168, // actionBarDefaultArchivedIcon -> actionBarDefaultIcon
  188: 78, // actionBarDefaultArchivedTitle -> windowBackgroundWhiteBlackText
  189: 175, // actionBarDefaultArchivedSearch -> actionBarDefaultSearch
  190:
      176, // actionBarDefaultArchivedSearchPlaceholder -> actionBarDefaultSearchPlaceholder
  191: 165, // actionBarBrowser -> actionBarDefault
  192: 59, // chats_onlineCircle -> windowBackgroundWhiteBlueText
  197: 196, // chats_nameArchived -> chats_name
  201: 240, // chats_archiveBackground -> chats_actionBackground
  202: 194, // chats_archivePinBackground -> chats_unreadCounterMuted
  203: 239, // chats_archiveIcon -> chats_actionIcon
  204: 239, // chats_archiveText -> chats_actionIcon
  206: 205, // chats_messageArchived -> chats_message
  207: 205, // chats_message_threeLines -> chats_message
  210: 209, // chats_nameMessageArchived -> chats_nameMessage
  211: 209, // chats_nameMessage_threeLines -> chats_nameMessage
  212: 209, // chats_nameMessageArchived_threeLines -> chats_nameMessage
  216: 215, // chats_date_bold -> chats_date
  220: 219, // chats_sentReadCheck -> chats_sentCheck
  237: 154, // chats_menuTopBackgroundCats -> avatar_backgroundActionBarBlue
  242: 194, // chats_archivePullDownBackground -> chats_unreadCounterMuted
  243: 240, // chats_archivePullDownBackgroundActive -> chats_actionBackground
  247: 21, // chat_attachCheckBoxBackground -> dialogRoundCheckBox
  251: 3, // chat_attachPermissionImage -> dialogTextBlack
  252: 380, // chat_attachPermissionMark -> chat_sentError
  253: 3, // chat_attachPermissionText -> dialogTextBlack
  254: 100, // chat_attachEmptyImage -> emptyListPlaceholder
  255: 264, // chat_inPollCorrectAnswer -> chat_attachLocationBackground
  256: 264, // chat_outPollCorrectAnswer -> chat_attachLocationBackground
  257: 261, // chat_inPollWrongAnswer -> chat_attachAudioBackground
  258: 261, // chat_outPollWrongAnswer -> chat_attachAudioBackground
  263: 262, // chat_attachContactText -> chat_attachContactBackground
  265: 261, // chat_attachPollBackground -> chat_attachAudioBackground
  266: 174, // chat_status -> actionBarDefaultSubtitle
  267: 659, // chat_inGreenCall -> calls_callReceivedGreenIcon
  271: 98, // actionBarActionModeReaction -> windowBackgroundGray
  272: 711, // actionBarActionModeReactionText -> chat_inReactionButtonText
  274: 475, // buttonNeutral -> chat_replyPanelLine
  275: 78, // buttonNeutralText -> windowBackgroundWhiteBlackText
  282: 659, // chat_outGreenCall -> calls_callReceivedGreenIcon
  285: 283, // chat_outSentCheckRead -> chat_outSentCheck
  286: 284, // chat_outSentCheckReadSelected -> chat_outSentCheckSelected
  289: 276, // chat_outMediaIcon -> chat_outBubble
  290: 277, // chat_outMediaIconSelected -> chat_outBubbleSelected
  301: 300, // chat_outReplyLine2 -> chat_outReplyLine
  314: 318, // chat_outAdminText -> chat_outTimeText
  315: 313, // chat_outAdminSelectedText -> chat_outTimeSelectedText
  323: 322, // chat_outAudioCacheSeekbar -> chat_outAudioSeekbar
  338: 438, // chat_outLinkSelectBackground -> chat_linkSelectBackground
  344: 339, // chat_outReactionButtonBackground -> chat_outLoader
  345: 439, // chat_outTextSelectionHighlight -> chat_textSelectBackground
  346: 525, // chat_outTextSelectionCursor -> chat_TextSelectionCursor
  349: 161, // chat_outPsaNameText -> avatar_nameInMessageGreen
  369: 268, // chat_inMediaIcon -> chat_inBubble
  370: 352, // chat_inMediaIconSelected -> chat_inBubbleSelected
  390: 161, // chat_inPsaNameText -> avatar_nameInMessageGreen
  393: 620, // chat_inQuote -> featuredStickers_addButtonPressed
  394: 300, // chat_outQuote -> chat_outReplyLine
  412: 414, // chat_inAdminText -> chat_inTimeText
  413: 415, // chat_inAdminSelectedText -> chat_inTimeSelectedText
  422: 421, // chat_inAudioCacheSeekbar -> chat_inAudioSeekbar
  487: 494, // chat_emojiSearchBackground -> chat_emojiPanelStickerPackSelector
  488: 491, // chat_emojiSearchIcon -> chat_emojiPanelIcon
  492: 491, // chat_emojiBottomPanelIcon -> chat_emojiPanelIcon
  495:
      493, // chat_emojiPanelStickerPackSelectorLine -> chat_emojiPanelIconSelected
  499:
      62, // chat_emojiPanelStickerSetNameHighlight -> windowBackgroundWhiteBlueText4
  524: 439, // chat_inTextSelectionHighlight -> chat_textSelectBackground
  525: 449, // chat_TextSelectionCursor -> chat_messagePanelCursor
  529: 38, // chat_editMediaButton -> dialogFloatingButton
  593: 102, // table_background -> graySection
  594: 101, // table_border -> divider
  599: 78, // profile_title -> windowBackgroundWhiteBlackText
  605: 157, // profile_status -> avatar_subtitleInProfileBlue
  608: 70, // profile_tabText -> windowBackgroundWhiteGrayText
  609: 83, // profile_tabSelectedText -> windowBackgroundWhiteBlueHeader
  610: 83, // profile_tabSelectedLine -> windowBackgroundWhiteBlueHeader
  611: 54, // profile_tabSelector -> listSelector
  615: 98, // sharedMedia_photoPlaceholder -> windowBackgroundGray
  619: 618, // featuredStickers_addButton2 -> featuredStickers_addButton
  621:
      620, // featuredStickers_removeButtonText -> featuredStickers_addButtonPressed
  626: 618, // changephoneinfo_image2 -> featuredStickers_addButton
  633: 239, // groupcreate_spanDelete -> chats_actionIcon
  644: 65, // location_sendLocationText -> windowBackgroundWhiteBlueText7
  646: 643, // location_sendLiveLocationIcon -> location_sendLocationIcon
  647: 68, // location_sendLiveLocationText -> windowBackgroundWhiteGreenText
  650: 3, // location_actionIcon -> dialogTextBlack
  651: 65, // location_actionActiveIcon -> windowBackgroundWhiteBlueText7
  652: 1, // location_actionBackground -> dialogBackground
  653: 2, // location_actionPressedBackground -> dialogBackgroundGray
  661: 520, // undo_background -> chat_gifSaveHintBackground
  662: 519, // undo_cancelColor -> chat_gifSaveHintText
  663: 519, // undo_infoColor -> chat_gifSaveHintText
  664: 494, // sheet_scrollUp -> chat_emojiPanelStickerPackSelector
  665: 672, // sheet_other -> player_actionBarItems
  666: 632, // bot_loadingIcon -> groupcreate_spanBackground
  668: 114, // gift_ribbon_soldout -> text_RedBold
  676: 675, // player_progressCachedBackground -> player_progressBackground
  689: 701, // statisticChartLine_blue -> color_blue
  691: 704, // statisticChartLine_red -> color_red
  692: 706, // statisticChartLine_golden -> color_yellow
  693: 700, // statisticChartLine_lightblue -> color_lightblue
  695: 705, // statisticChartLine_orange -> color_orange
  696: 707, // statisticChartLine_indigo -> color_purple
  697: 707, // statisticChartLine_purple -> color_purple
  698: 708, // statisticChartLine_cyan -> color_cyan
  709: 461, // chat_inReactionButtonBackground -> chat_inLoader
  710: 297, // chat_outReactionButtonText -> chat_outPreviewInstantText
  711: 385, // chat_inReactionButtonText -> chat_inPreviewInstantText
  712: 49, // chat_inReactionButtonTextSelected -> windowBackgroundWhite
  713: 49, // chat_outReactionButtonTextSelected -> windowBackgroundWhite
  714: 276, // chat_reactionServiceButtonBackgroundSelected -> chat_outBubble
  715: 354, // chat_reactionServiceButtonTextSelected -> chat_messageTextOut
  736: 193, // topics_unreadCounter -> chats_unreadCounter
  737: 205, // topics_unreadCounterMuted -> chats_message
  757: 49, // iv_background -> windowBackgroundWhite
  758: 98, // iv_backgroundGray -> windowBackgroundGray
  759: 618, // iv_ab_progress -> featuredStickers_addButton
  760: 98, // iv_navigationBackground -> windowBackgroundGray
  761: 78, // share_linkText -> windowBackgroundWhiteBlackText
  762: 98, // share_linkBackground -> windowBackgroundGray
  763: 78, // share_icon -> windowBackgroundWhiteBlackText
  764: 450, // glass_defaultIcon -> chat_messagePanelIcons
  765: 447, // glass_defaultText -> chat_messagePanelText
  766: 1, // glass_targetMainTabs -> dialogBackground
  767: 1, // glass_targetMainTopPanel -> dialogBackground
  768: 451, // glass_tabSelected -> chat_messagePanelSend
  769: 451, // glass_tabSelectedText -> chat_messagePanelSend
  770: 78, // glass_tabUnselected -> windowBackgroundWhiteBlackText
  774: 78, // telegram_color_dialogsLogo -> windowBackgroundWhiteBlackText
  775: 451, // telegram_color -> chat_messagePanelSend
  776: 62, // telegram_color_text -> windowBackgroundWhiteBlueText4
};

/// Keys whose resolved color is forced opaque (`color |= 0xFF000000`)
/// in Theme.getColor.
const List<int> kForcedOpaqueKeys = <int>[
  49, // windowBackgroundWhite
  98, // windowBackgroundGray
  165, // actionBarDefault
  185, // actionBarDefaultArchived
];
