#!/usr/bin/env python3
"""emit_dart.py — Stages 2+3 of the telegram_ui token codegen pipeline.

Reads the checked-in `theme_tokens.json` intermediate (produced by
gen_tokens.py) plus the `groups.toml` prefix -> typed-group mapping and
emits the committed Dart token files into
`flutter/telegram_ui/lib/src/tokens/`:

  theme_keys.g.dart              777 const int ordinals (TelegramColorKey)
  theme_key_names.g.dart         attheme name <-> key maps
  theme_fallbacks.g.dart         fallback table + forced-opaque key list
  palettes/default_colors.g.dart kDefaultColors (dense, length colorsCount)
  palettes/theme_<name>.g.dart   per-bundled-theme sparse overlay maps
  palettes/palettes.g.dart       barrel + kBundledThemes registry
  color_scheme.g.dart            typed groups from groups.toml + catch-all

Output is byte-stable and dartfmt-clean by construction (the emitter writes
exactly what `dart format` would produce — verified by the package test
suite / CI running `dart format --set-exit-if-changed`).  Headers are
stamped with the SHA-256 of the inputs, so upstream churn shows up as
reviewable diffs.

Usage:
  python3 emit_dart.py           # (re)write the generated files
  python3 emit_dart.py --check   # regenerate to memory, byte-compare, exit 1 on drift
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tomllib
from pathlib import Path

TOOL_DIR = Path(__file__).resolve().parent
DEFAULT_TOKENS = TOOL_DIR / "theme_tokens.json"
DEFAULT_GROUPS = TOOL_DIR / "groups.toml"
DEFAULT_OUT_DIR = TOOL_DIR.parent / "telegram_ui" / "lib" / "src" / "tokens"

LINE_WIDTH = 80
KEYS_CLASS = "TelegramColorKey"

# Words that cannot (or must not) be used as generated member names: Dart
# reserved words, built-in identifiers, and Object/API members of the
# generated classes.
RESERVED = {
    "assert", "break", "case", "catch", "class", "const", "continue",
    "default", "do", "else", "enum", "extends", "false", "final", "finally",
    "for", "if", "in", "is", "new", "null", "rethrow", "return", "super",
    "switch", "this", "throw", "true", "try", "var", "void", "while", "with",
    "abstract", "as", "covariant", "deferred", "dynamic", "export",
    "extension", "external", "factory", "get", "implements", "import",
    "interface", "late", "library", "mixin", "operator", "part", "required",
    "set", "static", "typedef", "await", "yield", "base", "sealed", "when",
    "hashCode", "runtimeType", "toString", "noSuchMethod", "resolve",
}


class EmitError(RuntimeError):
    pass


def warn(msg: str) -> None:
    print(f"emit_dart.py: warning: {msg}", file=sys.stderr)


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def is_identifier(name: str) -> bool:
    if not name or name in RESERVED:
        return False
    if not (name[0].isalpha() or name[0] in "_$"):
        return False
    return all(c.isalnum() or c in "_$" for c in name)


def camelize(name: str) -> str:
    """snake-ish -> lowerCamelCase: 'wallpaper_gradient_to1' -> 'wallpaperGradientTo1',
    'White' -> 'white'."""
    parts = [p for p in name.split("_") if p]
    if not parts:
        return ""
    first = parts[0][0].lower() + parts[0][1:]
    rest = [p[0].upper() + p[1:] for p in parts[1:]]
    return first + "".join(rest)


def theme_ident(theme_name: str) -> tuple[str, str]:
    """'Dark Blue' -> ('theme_dark_blue', 'kDarkBlueTheme')."""
    words = theme_name.split()
    snake = "_".join(w.lower() for w in words)
    pascal = "".join(w[0].upper() + w[1:].lower() for w in words)
    return f"theme_{snake}", f"k{pascal}Theme"


# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------


def header(tokens_sha: str, groups_sha: str | None, tokens_meta: dict) -> str:
    lines = [
        "// GENERATED CODE - DO NOT MODIFY BY HAND.",
        "//",
        "// Generated by flutter/tool/emit_dart.py from flutter/tool/theme_tokens.json",
        "// (token codegen pipeline stages 2-3, flutter/docs/ARCHITECTURE.md section 4.3).",
        "// Regenerate: python3 flutter/tool/gen_tokens.py && python3 flutter/tool/emit_dart.py",
        "// Drift gate:  both scripts support --check (byte-compare, nonzero exit).",
        "//",
        "// Inputs:",
        f"//   theme_tokens.json sha256: {tokens_sha}",
    ]
    if groups_sha is not None:
        lines.append(f"//   groups.toml       sha256: {groups_sha}")
    lines += [
        "// Upstream Java sources (paths + sha256 recorded in theme_tokens.json meta):",
    ]
    for label, src in tokens_meta["sources"].items():
        lines.append(f"//   {label}: {src['sha256']}")
    lines += [
        "//",
        "// Output is dartfmt-clean by construction: `dart format` must be a no-op",
        "// on this file (enforced in CI with `dart format --set-exit-if-changed`).",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Individual files
# ---------------------------------------------------------------------------


def emit_theme_keys(tokens: dict, head: str) -> str:
    keys = tokens["keys"]
    out = [head]
    out.append("// ignore_for_file: constant_identifier_names")
    out.append("")
    out.append("/// Dense int color-key ordinals, identical to the `key_* = colorsCount++`")
    out.append("/// declaration order in Theme.java (each name below is the Java constant")
    out.append(f"/// minus its `key_` prefix). {len(keys)} keys.")
    out.append(f"abstract final class {KEYS_CLASS} {{")
    for i, key in enumerate(keys):
        if not is_identifier(key):
            raise EmitError(f"key {key!r} is not a valid Dart identifier")
        out.append(f"  static const int {key} = {i};")
    out.append("")
    out.append("  /// Theme.colorsCount — the size of every dense color table.")
    out.append(f"  static const int colorsCount = {len(keys)};")
    out.append("}")
    return "\n".join(out) + "\n"


def emit_theme_key_names(tokens: dict, head: str) -> str:
    keys = tokens["keys"]
    names = tokens["names"]
    out = [head]
    out.append("/// Serialized `.attheme` name -> key ordinal, ported verbatim from")
    out.append("/// ThemeColors.createColorKeysMap(). The string is NOT always the Java")
    out.append("/// identifier minus `key_` (e.g. listSelector -> 'listSelectorSDK21',")
    out.append("/// graySectionText -> 'key_graySectionText' upstream typo) — never derive")
    out.append("/// these names by string munging.")
    out.append("const Map<String, int> kAttThemeNames = <String, int>{")
    for i, key in enumerate(keys):
        if key in names:
            out.append(f"  '{names[key]}': {i},")
    out.append("};")
    out.append("")
    out.append("/// Key ordinal -> serialized `.attheme` name; null for the keys that have")
    out.append("/// no entry in createColorKeysMap() and therefore cannot appear in a")
    out.append("/// theme file.")
    out.append("const List<String?> kColorKeyNames = <String?>[")
    for key in keys:
        if key in names:
            out.append(f"  '{names[key]}',")
        else:
            out.append(f"  null, // {key}")
    out.append("];")
    return "\n".join(out) + "\n"


def emit_theme_fallbacks(tokens: dict, head: str) -> str:
    keys = tokens["keys"]
    ordinal = {k: i for i, k in enumerate(keys)}
    fallbacks = tokens["fallbacks"]
    forced = tokens["meta"]["forcedOpaqueKeys"]
    out = [head]
    out.append("/// Key -> fallback key (Theme.java `fallbackKeys` static table,")
    out.append(f"/// {len(fallbacks)} entries). Resolved at lookup time — currentColors[key] ??")
    out.append("/// currentColors[fallback[key]] ?? defaults[key] — never flattened, so")
    out.append("/// sparse overrides keep fallback behavior (ARCHITECTURE.md section 4.1).")
    out.append("const Map<int, int> kFallbackKeys = <int, int>{")
    for key in keys:
        if key in fallbacks:
            dst = fallbacks[key]
            line = f"  {ordinal[key]}: {ordinal[dst]}, // {key} -> {dst}"
            if len(line) <= LINE_WIDTH:
                out.append(line)
            else:
                # dartfmt counts trailing comments in line width and splits
                # long map entries after the ':' with +4 continuation indent.
                out.append(f"  {ordinal[key]}:")
                out.append(f"      {ordinal[dst]}, // {key} -> {dst}")
    out.append("};")
    out.append("")
    out.append("/// Keys whose resolved color is forced opaque (`color |= 0xFF000000`)")
    out.append("/// in Theme.getColor.")
    out.append("const List<int> kForcedOpaqueKeys = <int>[")
    for key in forced:
        out.append(f"  {ordinal[key]}, // {key}")
    out.append("];")
    return "\n".join(out) + "\n"


def emit_default_colors(tokens: dict, head: str) -> str:
    keys = tokens["keys"]
    defaults = tokens["defaults"]
    no_default = set(tokens["meta"]["keysWithoutDefault"])
    out = [head]
    out.append("/// ThemeColors.createDefaultColors() as a dense ARGB table of length")
    out.append(f"/// {KEYS_CLASS}.colorsCount. Keys with no upstream assignment are")
    out.append("/// 0x00000000, matching Java's zero-initialized array (they resolve via")
    out.append("/// kFallbackKeys or are runtime-computed, e.g. chat_serviceBackground).")
    out.append("const List<int> kDefaultColors = <int>[")
    for i, key in enumerate(keys):
        if key in defaults:
            out.append(f"  {defaults[key]}, // {i} {key}")
        else:
            assert key in no_default
            out.append(f"  0x00000000, // {i} {key} (no default upstream)")
    out.append("];")
    return "\n".join(out) + "\n"


def emit_theme_palette(tokens: dict, theme_name: str, head: str) -> str:
    keys = tokens["keys"]
    ordinal = {k: i for i, k in enumerate(keys)}
    overlay = tokens["themes"][theme_name]
    meta = tokens["meta"]["themes"][theme_name]
    _, const_name = theme_ident(theme_name)
    out = [head]
    out.append(f"/// Sparse color overlay for the bundled Android theme '{theme_name}'")
    out.append(f"/// ({meta['asset']}, {len(overlay)} entries), parsed with Android-exact")
    out.append("/// `.attheme` semantics. Keys not present resolve through kFallbackKeys")
    out.append("/// and then kDefaultColors. Ordinal 0 (wallpaperFileOffset) mirrors")
    out.append("/// Android's parser, which always stores the wallpaper byte offset")
    out.append("/// (-1 when the file has no WPS marker) — it is not a color.")
    if meta["droppedFinalLine"] is not None:
        out.append("///")
        out.append(f"/// Android parity note: the asset's final line has no trailing newline")
        out.append("/// and is silently dropped by Theme.getThemeFileValues — replicated here")
        out.append(f"/// (dropped: `{meta['droppedFinalLine']}`).")
    out.append(f"const Map<int, int> {const_name} = <int, int>{{")
    for key, value in overlay.items():
        out.append(f"  {ordinal[key]}: {value}, // {key}")
    out.append("};")
    return "\n".join(out) + "\n"


def emit_palettes_barrel(tokens: dict, head: str) -> str:
    theme_names = list(tokens["themes"])
    out = [head]
    for name in theme_names:
        snake, _ = theme_ident(name)
        out.append(f"import '{snake}.g.dart';")
    out.append("")
    out.append("export 'default_colors.g.dart';")
    for name in theme_names:
        snake, _ = theme_ident(name)
        out.append(f"export '{snake}.g.dart';")
    out.append("")
    out.append("/// Bundled sparse theme overlays keyed by their Android registration name")
    out.append("/// (Theme.java static init; 'Blue' is the default day theme and 'Dark Blue'")
    out.append("/// the default night theme).")
    out.append("const Map<String, Map<int, int>> kBundledThemes = <String, Map<int, int>>{")
    for name in theme_names:
        _, const_name = theme_ident(name)
        out.append(f"  '{name}': {const_name},")
    out.append("};")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# color_scheme.g.dart
# ---------------------------------------------------------------------------


def load_groups(groups_path: Path) -> tuple[dict, list[str]]:
    with groups_path.open("rb") as fh:
        data = tomllib.load(fh)
    groups = data.get("groups", {})
    expected_ungrouped = data.get("ungrouped", {}).get("expected", [])
    for accessor, cfg in groups.items():
        if not is_identifier(accessor):
            raise EmitError(f"groups.toml: accessor {accessor!r} is not a valid identifier")
        if not is_identifier(cfg.get("class", "")):
            raise EmitError(f"groups.toml: group {accessor!r} has invalid class name")
        if not cfg.get("prefixes"):
            raise EmitError(f"groups.toml: group {accessor!r} has no prefixes")
    classes = [cfg["class"] for cfg in groups.values()]
    if len(set(classes)) != len(classes):
        raise EmitError("groups.toml: duplicate class names")
    return groups, expected_ungrouped


def assign_groups(keys: list[str], groups: dict) -> tuple[dict[str, list[tuple[str, str]]], list[str]]:
    """Returns ({accessor: [(member, key), ...]}, ungrouped_keys).

    Longest-prefix-wins matching; member = camelized remainder, falling back
    to the camelized full key name when the remainder is unusable.
    """
    by_prefix: list[tuple[str, str]] = []  # (prefix, accessor)
    for accessor, cfg in groups.items():
        for prefix in cfg["prefixes"]:
            by_prefix.append((prefix, accessor))
    by_prefix.sort(key=lambda pa: -len(pa[0]))

    assigned: dict[str, list[tuple[str, str]]] = {a: [] for a in groups}
    ungrouped: list[str] = []
    for key in keys:
        for prefix, accessor in by_prefix:
            if key.startswith(prefix):
                remainder = key[len(prefix):]
                member = camelize(remainder)
                if not is_identifier(member):
                    # Empty remainder, leading digit, or reserved word:
                    # fall back to the camelized full key name.
                    member = camelize(key)
                if not is_identifier(member):
                    raise EmitError(f"cannot derive member name for key {key!r}")
                assigned[accessor].append((member, key))
                break
        else:
            ungrouped.append(key)

    for accessor, members in assigned.items():
        seen: dict[str, str] = {}
        for member, key in members:
            if member in seen:
                raise EmitError(
                    f"group {accessor!r}: member {member!r} derived from both "
                    f"{seen[member]!r} and {key!r}"
                )
            seen[member] = key
    return assigned, ungrouped


def _wrap_arrow(head_part: str, call: str, arg: str) -> list[str]:
    """Replicates dart format's tall style for `head => call(arg);` members.

    1. one line if it fits;
    2. else break after `=>` (continuation indent +4) if the body fits;
    3. else block-split the argument list (args at +2, closing `);` at the
       member indent) — observed dart format 3.x behavior.
    """
    one = f"  {head_part} => {call}({arg});"
    if len(one) <= LINE_WIDTH:
        return [one]
    cont = f"      {call}({arg});"
    if len(cont) <= LINE_WIDTH:
        return [f"  {head_part} =>", cont]
    return [f"  {head_part} => {call}(", f"    {arg},", "  );"]


def _getter_lines(member: str, key: str, resolver: str) -> list[str]:
    return [f"  /// key_{key}"] + _wrap_arrow(
        f"Color get {member}", resolver, f"{KEYS_CLASS}.{key}"
    )


def emit_color_scheme(tokens: dict, groups_path: Path, head: str) -> str:
    keys = tokens["keys"]
    groups, expected_ungrouped = load_groups(groups_path)
    assigned, ungrouped = assign_groups(keys, groups)

    newly_ungrouped = [k for k in ungrouped if k not in set(expected_ungrouped)]
    if newly_ungrouped:
        warn(
            f"{len(newly_ungrouped)} key(s) fell into the UngroupedColors catch-all "
            f"but are not listed in groups.toml [ungrouped].expected: "
            + ", ".join(newly_ungrouped)
            + " — consider adding them to a group (or to the expected list)."
        )
    stale_expected = [k for k in expected_ungrouped if k not in set(ungrouped)]
    if stale_expected:
        warn(
            "groups.toml [ungrouped].expected lists keys that are no longer "
            "ungrouped (or no longer exist): " + ", ".join(stale_expected)
        )

    out = [head]
    out.append("import 'dart:ui' show Color;")
    out.append("")
    out.append("import 'theme_keys.g.dart';")
    out.append("")
    out.append("/// Resolves a [TelegramColorKey] ordinal into a themed [Color] (the")
    out.append("/// Theme.getColor analog supplied by the theme runtime).")
    out.append("typedef TelegramColorResolver = Color Function(int key);")
    out.append("")
    out.append("/// Typed accessor groups over the flat token space, generated from")
    out.append("/// flutter/tool/groups.toml. Example: `scheme.chat.inBubble` instead of")
    out.append(f"/// `resolve({KEYS_CLASS}.chat_inBubble)`. Keys outside every group are")
    out.append("/// reachable through [ungrouped] (and always through [resolve]).")
    out.append("class TelegramColorScheme {")
    out.append("  const TelegramColorScheme(this.resolve);")
    out.append("")
    out.append("  /// The underlying resolver — the full-key-space escape hatch.")
    out.append("  final TelegramColorResolver resolve;")
    for accessor, cfg in groups.items():
        out.append("")
        out.append(f"  /// {cfg['doc']}")
        out.extend(_wrap_arrow(f"{cfg['class']} get {accessor}", cfg["class"], "resolve"))
    out.append("")
    out.append("  /// Catch-all for keys not covered by any group in groups.toml.")
    out.append("  UngroupedColors get ungrouped => UngroupedColors(resolve);")
    out.append("}")

    for accessor, cfg in groups.items():
        out.append("")
        out.append(f"/// {cfg['doc']}")
        out.append(f"class {cfg['class']} {{")
        out.append(f"  const {cfg['class']}(this._resolve);")
        out.append("")
        out.append("  final TelegramColorResolver _resolve;")
        for member, key in assigned[accessor]:
            out.append("")
            out.extend(_getter_lines(member, key, "_resolve"))
        out.append("}")

    out.append("")
    out.append("/// Keys that match no prefix in groups.toml — the generation-stable")
    out.append("/// catch-all (new upstream keys land here before being grouped).")
    out.append("class UngroupedColors {")
    out.append("  const UngroupedColors(this._resolve);")
    out.append("")
    out.append("  final TelegramColorResolver _resolve;")
    seen: dict[str, str] = {}
    for key in ungrouped:
        member = camelize(key)
        if not is_identifier(member):
            raise EmitError(f"cannot derive ungrouped member name for {key!r}")
        if member in seen:
            raise EmitError(
                f"ungrouped member {member!r} derived from both {seen[member]!r} and {key!r}"
            )
        seen[member] = key
        out.append("")
        out.extend(_getter_lines(member, key, "_resolve"))
    out.append("}")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def build_files(tokens_path: Path, groups_path: Path) -> dict[str, str]:
    tokens = json.loads(tokens_path.read_text(encoding="utf-8"))
    tokens_sha = sha256_file(tokens_path)
    groups_sha = sha256_file(groups_path)
    meta = tokens["meta"]

    head = header(tokens_sha, None, meta)
    head_groups = header(tokens_sha, groups_sha, meta)

    files: dict[str, str] = {
        "theme_keys.g.dart": emit_theme_keys(tokens, head),
        "theme_key_names.g.dart": emit_theme_key_names(tokens, head),
        "theme_fallbacks.g.dart": emit_theme_fallbacks(tokens, head),
        "palettes/default_colors.g.dart": emit_default_colors(tokens, head),
        "palettes/palettes.g.dart": emit_palettes_barrel(tokens, head),
        "color_scheme.g.dart": emit_color_scheme(tokens, groups_path, head_groups),
    }
    for theme_name in tokens["themes"]:
        snake, _ = theme_ident(theme_name)
        files[f"palettes/{snake}.g.dart"] = emit_theme_palette(tokens, theme_name, head)
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="regenerate to memory and byte-compare against the "
                             "committed files; exit 1 on drift")
    parser.add_argument("--tokens", type=Path, default=DEFAULT_TOKENS)
    parser.add_argument("--groups", type=Path, default=DEFAULT_GROUPS)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = parser.parse_args(argv)

    files = build_files(args.tokens, args.groups)

    # Stale-file scan: only inside palettes/, the one directory this emitter
    # owns outright (a renamed upstream theme would otherwise leave a stale
    # overlay behind).  Sibling .g.dart files in tokens/ belong to other
    # generators (gen_shader_bindings.py, extract_spec.yaml emission).
    expected_paths = {args.out_dir / rel for rel in files}
    palettes_dir = args.out_dir / "palettes"
    stale = [
        p for p in palettes_dir.glob("*.g.dart")
        if p not in expected_paths
    ] if palettes_dir.exists() else []
    for p in stale:
        warn(f"stale generated file not in the emit set: {p}")

    if args.check:
        drift = []
        for rel, content in sorted(files.items()):
            path = args.out_dir / rel
            if not path.exists():
                drift.append(f"missing: {path}")
            elif path.read_bytes() != content.encode("utf-8"):
                drift.append(f"stale:   {path}")
        if drift or stale:
            for d in drift:
                print(f"emit_dart.py --check: {d}", file=sys.stderr)
            print(
                "emit_dart.py --check: drift detected; re-run "
                "python3 flutter/tool/emit_dart.py",
                file=sys.stderr,
            )
            return 1
        print(f"emit_dart.py --check: {len(files)} generated files are up to date")
        return 0

    for rel, content in sorted(files.items()):
        path = args.out_dir / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
